name: hackpay
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  collection: ^1.18.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_svg_plus: ^2.0.13+1
  get_it: ^8.0.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
