name: CI Pipeline

on:
  push:
    branches:
      - dev

env:
  flutter_version: "3.24.3"

jobs:
  run-tests:
    runs-on: macOS-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Launch emulator
        uses: futureware-tech/simulator-action@v4
        with:
          model: 'iPhone 14'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true


      - name: Install dependencies
        run: flutter pub get

      - name: Format code
        run: dart format . --set-exit-if-changed

      - name: Lint analysis
        run: flutter analyze --no-pub

      - name: Run integration tests
        run: flutter test integration_test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info